### ISSUE TITLE
Assists in measuring at right angles

### ISSUE THREAD

**Issue by rusty-snake** [streetcomplete/StreetMeasure#10]
The precision of AR Core is pretty impressive. The biggest Measurement deviation seems to be the measureing angle at which you cross the road. Could SM give some assistant here? I.e. a T at the both ends of the line that you can align at curbs.

**Comment by westnordost** [comment]
I understand what you mean, and the best way to reduce imprecision here is to just use the shortest distance, because the shortest distance is always orthogonal to the road. I.e. after crossing the road and aiming at the curb to your feet, sway a bit to the left and to the right and find the point at which the minimum width is displayed. 
This is more precise than trusting in an additional UI element.

![imagen](https://github.com/user-attachments/assets/b3a1d381-81b1-471f-b8d0-23c169482f4c)

**Comment by rusty-snake** [comment]
Ok I started reading your comment and first I thought that's exactly my problem, that I want to avoid the 10° offset. But then you made the point "way a bit to the left and to the right and find the point at which the minimum width is displayed". Maybe it's worth to add this to the measuring suggestions in the app.

**Comment by westnordost** [comment]
Mh, I don't know, rather not. This is nothing specific for the technology, you would do the same with a measuring tape.
