### ISSUE TITLE
angle limit

### ISSUE THREAD

**Issue by shigekilft** [streetcomplete/StreetMeasure#14]
Hello, thank you for sharing this amazing project!

I have a question about the function `updateVerticalMeasuring(cameraPose: Pose)` in the `MeasureActivity` class.  
Specifically, at **line 548**, I noticed the following condition:  

```kotlin
if (normalizedCameraAngle < -pi2 * 2 / 3 || normalizedCameraAngle > +pi2 * 1 / 2) {
```

Could you please explain the reasoning behind this angle restriction?
​Is this meant to address specific edge cases, or does it serve a particular purpose in the measurement logic?

Your clarification would help me better understand this part of the code.
Thank you for your time and for maintaining this excellent project!

**Comment by westnordost** [comment]
If I remember correctly, the limit is chosen arbitrarily, but there needs to be a reasonable limit. The steeper the angle, the higher the imprecision because even the smallest change in angle will result in a big difference in measured length.

![imagen](https://github.com/user-attachments/assets/c7626f06-f8d2-4186-8878-5fdcc3c93fba)

Only 5° difference but 1/3 length difference. It gets more and more extreme the closer you are to 90°.
