### ISSUE TITLE
StreetMeasure freezes on start

### ISSUE THREAD

**Issue by guerda** [streetcomplete/StreetMeasure#6]
I have used StreetMeasure with Street complete successfully in the past with my current phone.
Since today the app just freezes on start. You see the initial camera picture but then it freezes. After a while the Android dialogue to close or wait comes up 

What have I tried?
* Force close and re open 
* Start as separate app and from Street Complete
* Clearing cache and storage for the app
* Reinstalling from Google Play
* Double checked the permissions

Nothing changed.

Version 1.3
Android 14
Pixel 7

**Comment by westnordost** [comment]
Hm well, nothing changed in the app. What about ARCore (Google Play Services for AR), did it update recently?

**Comment by guerda** [comment]
It updated on 25.11.2023 according to Google Play Store.

![Screenshot_20231226-214831.png](https://github.com/streetcomplete/StreetMeasure/assets/230782/14e8b74f-4493-414e-b18c-73625536c1a1)

I saw that on 14.12.2023, the "Pixel Camera Services" were updated. Not sure if that could be related.

Any idea how I can troubleshoot or give you more information?

**Comment by westnordost** [comment]
Hmm, .. .I should get "Application not responding" errors in the google play console after a few days they happened from users unless that setting (error reporting?) is turned off somewhere in the Android system settings. I'll have a look at it in a few days. Not sure if it is helpful though. Since it is not a crash, I don't get a stack trace or anything.

**Comment by westnordost** [comment]
Hm but since you are asking if there is anything you could do to help troubleshoot or find more information about the issue. There are two, but both might be too much work for you. I still want to mention them:

- if you have an Android development environment set up or would like to do that (basically, download & install Android Studio), you could open this project and compile it yourself. Maybe you are able to see why the app is freezing yourself in the logs that are displayed there, or by setting breakpoints in the code (I can help there), see, what it is that is being executed last before it freezes up.

- You could try to install an older version of Google Play Services for AR to rule out that this app is the root of the problem

Because, the issue for me is, that Google Play Services for AR does not support my current phone's operating system (LineageOS). I.e. it does not recognize my device as one of the supported devices even though it should be, so I can't even use and test this app anymore on my device.

**Comment by guerda** [comment]
Now it gets interesting. While trying to downgrade to 1.40, I deactivated the app Google Services for AR (arcore). For fun, I started street measure and it works just fine! 
As soon as I activate the service, it freezes again. 

The I deleted the cache and storage for arcore and now street measure works again just fine.

So the culprit seemed to be arcore but it's strange how the app reacts.

**Comment by westnordost** [comment]
What, that's impossible! The app cannot work without Google Play Services for AR! I mean, can you actually do measurements without arcore?

**Comment by guerda** [comment]
Yes, I am able to measure distances. I have no idea how that works though...

Can I send you a screen grab?

**Comment by westnordost** [comment]
No, I believe you. But, this is really strange. The ARCore dependency that is included within the app as far as I know literally doesn't do anything else than talk with the installed Google Play Services for AR to do the actual heavy lifting of AR calculation. (Otherwise, the app "Google Play Services for AR" would have no purpose?)

In summary, I am confused.

**Comment by guerda** [comment]
I am also completely confused to be honest.. I will observe if anything changes in the future

**Comment by westnordost** [comment]
From reading the issue history, it looks like it was an issue with the setup (i.e. ARCore not installed correctly or something), and also solved for the issue reporter. So, I'll close this.
