### ISSUE TITLE
Migrate to API 34

### ISSUE THREAD

**Issue by Jean-BaptisteC** [streetcomplete/StreetMeasure#8]
Stm use API 33, and Google give 2 years to migrate to the latest API (Google removes app from Play Store if migration is not done). We have 1 years to do the migration.

Todo:

- [ ] Migrate compileSdk and targetSdk to 34
- [ ]  Bump dependencies (do you want bump material library, this library continue to grow up and take a lot of space)
- [ ] Enable [OnBackInvokedCallback](https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture) feature (only on manifest we don't use onBackPressed in activity)
- [ ] Generate locales config (we can save few Kb)

Cc @westnordost

**Comment by westnordost** [comment]
Would you test this?

https://www.westnordost.de/misc/StreetMeasure-v1.4.apk

I continue to not have a device with which I can properly test.

I added a feature: That you can turn on flash of your camera in order to make it work better when it is not bright outside. Could someone test whether this works fine? (You need a device that has a camera flash for that to work)

@RubenKelevra You can use this app, right? Could you test the new version?

**Comment by RubenKelevra** [comment]
Yeah sure I use the app. Does it work with SC 58.x? Because 59.x does not launch anymore for me.

**Comment by RubenKelevra** [comment]
> @RubenKelevra You can use this app, right? Could you test the new version?

Starts, measures vertical and horizontal fine, flashlight works and can be called from SCEE correctly. 

Only issue I saw is while trying to install it as an update. It first said it would update, and then complained about a conflict with an installed program. Not sure Maybelline because my version was from the Playstore before? 

I usually don't install APKs that often.

**Comment by westnordost** [comment]
It should have the same signature as the one from Google Play... weird.

**Comment by RubenKelevra** [comment]
![Screenshot_2024-08-27-23-49-47-617-edit_com google android packageinstaller](https://github.com/user-attachments/assets/f00e7a1c-bdbf-4b77-abfd-863fd01b01c9)

![Screenshot_2024-08-27-23-50-05-988-edit_com android vending](https://github.com/user-attachments/assets/557e470d-1bb6-4a29-a88f-ba3bf4a4b326)

And then I confirmed to install, after that check was successful. And:

![Screenshot_2024-08-27-23-50-22-864-edit_com google android packageinstaller](https://github.com/user-attachments/assets/4841fcfa-886d-4505-97fb-9eb394d81630)

**Comment by westnordost** [comment]
Hm, well, curious. So the apps on google play use a different signature it seems. Anyway, as the new feature works, I've released it. Thanks for testing!

**Comment by RubenKelevra** [comment]
Welcome!
